// <auto-generated />
using KitabMawkout.Data.MyData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitabMawkout.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251202122814_AddWaitTimes")]
    partial class AddWaitTimes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("KitabMawkout.Data.MyData.MySetting", b =>
                {
                    b.Property<int>("MySettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsrWait")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DesMasjid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DohrWait")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FadjWait")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IshabWait")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("MoghrebWait")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MyCalculationMethode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MyMadhab")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MySettingsId");

                    b.ToTable("MySettings");
                });
#pragma warning restore 612, 618
        }
    }
}
